const url = "http://localhost:3000";
export const LoginRoutes = url+"/auth/login";
export const RegisterRoutes = url+"/auth/register";
export const fetchNoteS = url+"/note?userId=";
export const DeleteRoutes = url+"/note/delete";
export const ViewRoutes = url+"/note/";
export const EditRoutes = url+"/note/edit";
export const CreateRoutes = url+"/note/create";
export const IdentifyMe = url+"/auth/";
export const nameAndemail = url+"/auth/profile/";
export const profile = url+"/auth/profile/";
export const globalNotes = url+"/note/global/public";
export const palette = url+"/auth/palette/";
export const IdentifyUser = url+"/auth/user/";
export const followUser = url+"/auth//:userId/follow";
export const unfollowUser = url+"/auth/:userId/unfollow";
